urg_node:
  ros__parameters:
    serial_port: "/dev/hokuyo"
    laser_frame_id: "laser_frame"
    laser_topic: "/scan"
    angle_offset: 0.0
    min_angle: -2.356194   # -135 degree
    max_angle: 2.356194     # 135 degree
